# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: translate_proto/translator.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'translate_proto/translator.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n translate_proto/translator.proto\x12\rtranslator.v1\"K\n\x10TranslateRequest\x12\x0c\n\x04text\x18\x01 \x01(\t\x12)\n\x08language\x18\x02 \x01(\x0e\x32\x17.translator.v1.Language\",\n\x11TranslateResponse\x12\x17\n\x0ftranslated_text\x18\x01 \x01(\t*\xa8\x01\n\x08Language\x12\x18\n\x14LANGUAGE_UNSPECIFIED\x10\x00\x12\x14\n\x10LANGUAGE_ENGLISH\x10\x01\x12\x14\n\x10LANGUAGE_ITALIAN\x10\x02\x12\x14\n\x10LANGUAGE_SPANISH\x10\x03\x12\x16\n\x12LANGUAGE_HUNGARIAN\x10\x04\x12\x13\n\x0fLANGUAGE_POLISH\x10\x05\x12\x13\n\x0fLANGUAGE_FRENCH\x10\x06\x32_\n\x0bTranslation\x12P\n\tTranslate\x12\x1f.translator.v1.TranslateRequest\x1a .translator.v1.TranslateResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'translate_proto.translator_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_LANGUAGE']._serialized_start=175
  _globals['_LANGUAGE']._serialized_end=343
  _globals['_TRANSLATEREQUEST']._serialized_start=51
  _globals['_TRANSLATEREQUEST']._serialized_end=126
  _globals['_TRANSLATERESPONSE']._serialized_start=128
  _globals['_TRANSLATERESPONSE']._serialized_end=172
  _globals['_TRANSLATION']._serialized_start=345
  _globals['_TRANSLATION']._serialized_end=440
# @@protoc_insertion_point(module_scope)
